config/routes.rb
Rails.application.routes.draw do
  post '/favorite/book_id' => 'favorites#create', as: 'favorite'
  delete '/favorite/book_id' => 'favorites#destroy', as: 'unfavorite'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only:[:new, :create, :show, :index, :destroy, :edit, :update]
  resources :users, only:[:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { maximum: 200 }
	validates :body, presence: true, length: { maximum: 200 }

	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book, counter_cache: :favorites_count
  belongs_to :user
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true, length: { minimum: 2, maximum: 20 }
         validates :introduction, length: { maximum: 50 }
         has_many :books, dependent: :destroy
         attachment :profile_image

         has_many :favorites, dependent: :destroy
         has_many :favorites_books, through: :favorites, source: :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except:[:about, :top]
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
  @book = Book.find_by(id: params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_variables

  def create
    favorite = current_user.likes.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    favorite = current_user.likes.find_by(book_id: @book.id)
    favorite .destroy
  end

  private

  def set_varoables
    @book = Book.find(params[:book_id])
    @id_name = "#favorite-link-#{@book.id}"
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

 def about
 end

 def top
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]
  before_action :correct_user, only: [:edit]
  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
  	@users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.new
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def about
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
  @user = User.find_by(id: params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bookcommon.html.erb
<h1>New book</h1>
<%= form_for(book) do |f| %>



<h4>Title</h4>
<div class="field row">
	<%= f.text_field :title, class: 'col-xs-12 book_title' %>
</div>

<h4>Opinion</h4>
<div class="field row">
	<%= f.text_area :body, class: 'col-xs-12' %>
</div><br>
<div class="row">
	<%= f.submit 'Create Book', class: 'btn btn-primary col-xs-12' %>
</div>

<% end %>

app/views/books/edit.html.erb
<br><br>
<% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
        <% end %>
<div class="container">
	<div class="row">
		<div class= "col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
				Title<br>
				<div class="col-xs-12"><%= f.text_field :title %></div><br>
				Opinion<br>
				<div class="col-xs-12"><%= f.text_area :body %></div><br>

				<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %><br>

				<%= link_to "Show", book_path(@book.id) %> | 
				<%= link_to "Back", books_path %>
			<% end %>
		</div>
		<div class ="col-md-3">
		</div>
	</div>
</div>

app/views/books/index.html.erb
<br><br>
<% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
        <% end %>

<div class = "container">
	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'users/usercommon', user: @user %>
			<%= render 'books/bookcommon', book: @book %>
		</div>

		<div class = "col-xs-9">
			<h1>Books</h1>

			<table class="table table-hover">
				<thead>
					<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th>favorite</th>
					<th>comments</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<% @books.each do |book| %>
							<td>
								<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, size:"50x50", fallback:"no_image.png", format:'png' %>
								</td><% end %>
							<td><%= link_to book.title, book_path(book.id)%></td>
							<td><%= book.body %></td>
							<td><%= render 'favorites/favorite', book: book %></td>
							<td>コメント数カウント</td>
					</tr>
				</tbody>
						<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<br><br>
<div class = "container">
	<% if flash[:notice] %>
      <div>
        <%= flash[:notice] %>
      </div>
	<% end %>

	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'users/usercommon', user: @user %>
			<%= render 'books/bookcommon', book: @book %>
		</div>

		<div class = "col-xs-9">
			<h1>Book detail</h1>
			<p></p>
			<table class="table table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td><%= attachment_image_tag @user, :profile_image, size:"50x50", fallback:"no_image.png", format:'png' %><br>
							<%= link_to @user.name, user_path(@user.id) %>
						</td>
						<td><%= link_to @book_detail.title, book_path %></td>
						<td><%= @book_detail.body %></td>
						
						<td><% if @user == current_user %>
							<%= link_to"Edit", edit_book_path, class: "btn-sm btn-success" %>
						</td>
						<td><%= link_to"Destroy", book_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger"%></td>
								<% end %>
						

					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
<div class ="favorite-link" id="favorite-link-<%= book.id %>">
  <% if current_user.favorites.find_by(book_id: book.id) %>
    <%= link_to unfavorite_path(book.id), method: :delete, remote: true do %>
      <div class = "iine__button">❤︎<%= book.favorites_count %></div>
      <% end %>
    <% else %>
    <% link_to favorite_path(book.id), method: :post, remote: true do %>
      <div class = "iine__button">♡<%= book.favorites_count %></div>
    <% end %>
  <% end %>
</div>

app/views/homes/about.html.erb
<br>
<br>
<div class="container">
<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!</h1>
<div>

app/views/homes/top.html.erb
<br><br>
<% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    
<div class="container">
	<div class ="row">
		<div class ="col-md-offset-3 col-md-6">
			<h1><strong>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers</strong>　!!</h1>
			In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers,<br>

			you can share and exchange your opinions , inpressions , and emotions<br>

			about various books!<br>

			<div class="btn-wrapper">
				<div class="row">

						<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
					<br>
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</div>
				<h1 class="jquery">Hello jQuery!</h1>
				<div id="container">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>
</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
        <header class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
                <nav class="nav navbar-nav navbar-left">
                    <span><h4> Bookers </h4> </span>
                </nav>
                <nav>
                    <ul class= "nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                        <li>
                            <%= link_to "　Home", user_path(current_user), class: "glyphicon glyphicon-home" %>
                        </li>
                        
                        <li>
                            <%= link_to "　Users", users_path, class: "glyphicon glyphicon-user" %>
                        </li>
                        
                        <li>
                            <%= link_to "　Books", books_path, class: "glyphicon glyphicon-book" %>
                        </li>
                        
                        <li>
                            <%= link_to "　logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
                        </li>
                        <% else %>
                        
                        <li>
                            <%= link_to "　Home", root_path, class: "glyphicon glyphicon-home" %>
                        </li>
                        <li>
                            <%= link_to "　About", home_about_path, class: "glyphicon glyphicon-link" %>
                        </li>
                        <li>
                            <%= link_to "　sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
                        </li>
                        <li>
                            <%= link_to "　login",  new_user_session_path, class: "glyphicon glyphicon-log-in" %>
                        </li>
                        <% end %>
                    
                    
                    </ul>
                </nav>
            </div>
        </header>
        <br>
        <br>
    </body>
    
    <%= yield %>

    <footer>
        <div class ="container">
            <div class ="row">
                <div class="col-xs-3 col-xs-offset-9">
                    <p>CopyRight Infratop.inc</p>
                </div>
            </div>
        </div>
    </footer>
    
</html>

app/views/users/_usercommon.html.erb
<h1>User info</h1>

<%= attachment_image_tag user, :profile_image, size:"100x100", fallback:"no_image.png", format:'png' %>

<table class="table condensed">
	<thead>
		<tr>
			<th></th>
			<th></th>
		</tr>
	</thead>

		<tbody>
			<tr>
				<td><strong>Name</strong></td>
				<td><%= user.name %></td>
			</tr>

			<tr>
				<td><strong>Introduction</strong></td>
				<td><%= user.introduction %><br></td>
			</tr>
		</tbody>
</table>
		<% if @user == current_user %>
			<%= link_to edit_user_path(current_user), method: :get do %>
			<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>
			<% else %>
			<%= link_to user_path(current_user), method: :get do %>
			<span class="col-xs-12 btn btn-default glyphicon glyphicon-wrench" aria-hidden="true"></span>
			<% end %>
		<% end %>

app/views/users/edit.html.erb
<br>
<br>
<% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
        <% end %>

<div class="container">
	<div class="row">
		<div class ="col-xs-12">
			<h1>User info</h1>

			<%= form_for(@user) do |f| %>
				<strong>Name</strong>
				<%= f.text_field :name %><br>
				<strong>Image</strong>
				<%= f.attachment_field :profile_image %><br>
				<strong>Introduction</strong>
				<%= f.text_area :introduction %><br><br>

				<%= f.submit "Update User" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<br><br>
<div class = "container">
	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'users/usercommon', user: @user %>
			<%= render 'books/bookcommon', book: @book %>
		</div>

		<div class = "col-xs-9">
			<h1>Users</h1>


			<table class="table table-hover">
				<thead>
					<tr>
					<th>image</th>
					<th>name</th>
					<th></th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<% @users.each do |user| %>

						<td><%= attachment_image_tag user, :profile_image, size:"60x60", fallback:"no_image.png", format:'png' %></td>
						<td><%= user.name %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<br><br>
<% if flash[:notice] %>
      <div>
        <%= flash[:notice] %>
      </div>
<% end %>

<div class = "container">
	<div class = "row">
		<div class = "col-xs-3">
			<%= render 'users/usercommon', user: @user %>
			<%= render 'books/bookcommon', book: @book %>
		</div>

		<div class = "col-xs-9">
			<h1>Books</h1>

			<table class="table table-hover">
				<thead>
					<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					</tr>
				</thead>

				<tbody>
					<tr>
			<% @books.each do |book| %>
				<td><%= attachment_image_tag @user, :profile_image, size:"60x60", fallback:"no_image.png", format:'png' %></td>
				<td><%= link_to book.title, book_path(book.id)%></td>
				<td><%= book.body %></td>
					</tr>
				</tbody>
			<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/top.html.erb
<br><br>
<% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    
<div class="container">
	<div class ="row">
		<div class ="col-md-offset-3 col-md-6">

			<h1><strong>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers</strong>　!!</h1>
			In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers,<br>

			you can share and exchange your opinions , inpressions , and emotions<br>

			about various books!<br>

			<div class="btn-wrapper">
				<div class="row">

						<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
					<br>
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
				</div>
			</div>
		</div>
	</div>
</div>